name: Git Lint
on:
  pull_request:
    branches:
    - "*"
jobs:
  lint:
    name: Git Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Install
      shell: bash
      run: python -m pip install gitlint
    - name: Lint
      shell: bash
      run: gitlint --commits "${{ github.event.pull_request.base.sha }}..HEAD"
